package controller;

import model.*;
import model.EncryptionStrategy;
import view.View;

public class Controller {
	private static View view;
	private static EncryptionStrategy currentStrategy;
	private static Message currentMessage;
	private static boolean keyWillBeGenerated = false; //used to determine if should ask the user for a key or if it should be generated by the program
	
	public static void main(String[] args){
		view = new View();
		view.displayText("Welcome to the message encryptor.");
		view.displayText("Written by Richard Myers, Vinhcent Vu, and Darian Thomas.");
		
		String userInput = view.presentMenu();
		while (!userInput.toLowerCase().equals("q")){
			int strategyChoice = Integer.parseInt(userInput);
			currentStrategy = getStrategyFromChoice(strategyChoice);
			Message message = null;
			String text = view.getMessageText();
			boolean encrypted = view.getDirectionChoice();
			if (keyWillBeGenerated && !encrypted){
				System.out.println("Keys will be generated, user selected encryption");
				message = new Message(text, encrypted);
			}
			else {
				String key = view.getKey();
				message = new Message(text, key, encrypted);
			}
			if (currentStrategy instanceof ElGamal || currentStrategy instanceof RSA) message = new MultiKeyMessage(message);
			Message modifiedMessage = null;
			if (encrypted) modifiedMessage = currentStrategy.decrypt(message);
			else try{
				modifiedMessage = currentStrategy.encrypt(message);
			}catch (Exception e){}
			if (!encrypted) view.displayKey(modifiedMessage.getKey());
			view.displayModifiedMessage(modifiedMessage.getText());
			userInput = view.presentMenu();
		}
		view.displayText("Exiting");
	}
	
	public static EncryptionStrategy getStrategyFromChoice(int choice){
		switch(choice){
		case 0: keyWillBeGenerated = true; return new AES();
		case 1: keyWillBeGenerated = false; return new Bitwise();
		case 2: keyWillBeGenerated = true; return new ElGamal();
		case 3: keyWillBeGenerated = true; return new RSA();
		case 4: keyWillBeGenerated = false; return new Shift();
		case 5: keyWillBeGenerated = false; return new Substitution();
		}
		return null;
	}
	
	
}
